jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Perform base checks
      run: ./gradlew demo:assembleDebug cameraview:publishToDirectory --stacktrace
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Execute emulator tests
      timeout-minutes: 30
      uses: reactivecircus/android-emulator-runner@v2.21.0
      with:
        api-level: ${{ matrix.EMULATOR_API }}
        arch: ${{ matrix.EMULATOR_ARCH }}
        disable-animations: true
        emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back emulated
          -camera-front emulated -gpu swiftshader_indirect
        profile: Nexus 5X
        script: ./.github/workflows/emulator_script.sh
    - continue-on-error: true
      name: Upload emulator tests artifact
      uses: actions/upload-artifact@v1
      with:
        name: emulator_tests_${{ matrix.EMULATOR_API }}
        path: ./cameraview/build/coverage_input/android_tests
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API:
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        include:
        - EMULATOR_API: 28
          EMULATOR_ARCH: x86_64
        - EMULATOR_API: 27
          EMULATOR_ARCH: x86_64
        - EMULATOR_API: 26
          EMULATOR_ARCH: x86_64
        - EMULATOR_API: 25
          EMULATOR_ARCH: x86
        - EMULATOR_API: 24
          EMULATOR_ARCH: x86
        - EMULATOR_API: 23
          EMULATOR_ARCH: x86
        - EMULATOR_API: 22
          EMULATOR_ARCH: x86
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Execute unit tests
      run: ./gradlew cameraview:runUnitTests --stacktrace
    - continue-on-error: true
      name: Upload unit tests artifact
      uses: actions/upload-artifact@v1
      with:
        name: unit_tests
        path: ./cameraview/build/coverage_input/unit_tests
  CODE_COVERAGE:
    name: Code Coverage Report
    needs:
    - ANDROID_UNIT_TESTS
    - ANDROID_EMULATOR_TESTS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Download unit tests artifact
      uses: actions/download-artifact@v1
      with:
        name: unit_tests
        path: ./cameraview/build/coverage_input/unit_tests
    - continue-on-error: true
      name: Download emulator tests artifact
      uses: actions/download-artifact@v1
      with:
        name: emulator_tests_27
        path: ./cameraview/build/coverage_input/android_tests
    - continue-on-error: true
      name: Create merged coverage report
      run: ./gradlew cameraview:computeCoverage
    - continue-on-error: true
      name: Upload merged coverage report (GitHub)
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: ./cameraview/build/coverage_output/xml
    - continue-on-error: true
      name: Upload merged coverage report (Codecov)
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        file: ./cameraview/build/coverage_output/xml/*
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
